import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavAuth from "../components/NavAuth";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <nav className="p-3 w-full h-1/6 bg-blue-400">
          <NavAuth />
        </nav>

        <div className="p-8 bg-blue-400">
          {children}
        </div>


        <footer className="mx-5 w-full h-[10vh] flex items-center justify-around bg-white rounded-t-2xl shadow-md">
          <div className="">
            <Link href="/">POS</Link>
          </div>

          <div>
            <p className="text-center text-gray-600">
              © {new Date().getFullYear()} POS System. All rights reserved.
            </p>
          </div>

          <div>
            <ul className="flex items-center gap-x-4">
              <li><Link href="/login">Login</Link></li>
              <li><Link href="/register">Register</Link></li>
            </ul>
          </div>

        </footer>
      </body>
    </html>
  );
}
