import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavAuth from "../components/NavAuth";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <nav className="p-3 w-full h-1/5 bg-blue-400 flex items-center justify-center">
          <NavAuth />
        </nav>

        <div className="relative p-8 bg-blue-400 z-10">
          {children}
        </div>


        <footer className="w-full h-[10vh] flex items-center justify-around bg-white rounded-t-2xl shadow-md md:sticky md:bottom-0">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
